[package]
name = "leetcode"
version = "0.1.0"
authors = ["Pinkie_Pie <897356263@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
fern = "0.6.0"
log = "0.4.13"
